version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile        # adjust if your Dockerfile name/path differs
    container_name: ccapi_api
    env_file: [./enviroment/.env.api]
    ports:
      - "8080:8080"                 # for localhost testing; use "127.0.0.1:8080:8080" if fronted by Nginx
    volumes:
      - api_cache:/app/cache
    restart: unless-stopped

volumes:
  api_cache:
